#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  mtr_S1_C1_1,     Drive_R,       tmotorTetrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Drive_L,       tmotorTetrix, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Header.h"

task Driver()
{
	while(true)
	{
		if(!drivefast && !driveslow){drivepower = normpower;}
		if(drivefast){drivepower = highpower;}
		if(lowpower){drivepower = lowpower;}

		if(!revmode)
		{
			motor[Drive_L] = leftdrive;
			motor[Drive_R] = rightdrive;
		}
		else
		{
			motor[Drive_L] = -1*rightdrive;
			motor[Drive_R] = -1*leftdrive;
		}
	}
}

task Driverrev()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(revbut && revmode)
		{
			revmode = false;
			while(revbut){wait1Msec(1);}
		}
		if(revbut && !revmode)
		{
			revmode = true;
			while(revbut){wait1Msec(1);}
		}
	}
}

task Gunner() {
	while (true) {
		// Do nothing.
	}
}

task main()
{
	waitForStart();
	startTask(Driver);
	startTask(Gunner);
	startTask(Driverrev);
	while(true)
	{
		if(driverstop){
			stopTask(Driver);
			motor[Drive_R] = 0;
			motor[Drive_L] = 0;
			while(driverstop){wait1Msec(1);}
			startTask(Driver);
			}

		if(gunnerstop){
			//stopTask(Gunner);
			motor[Conv1] = 0;
			motor[Conv2] = 0;
			motor[Conv3] = 0;
			motor[Extend] = 0;
			while(gunnerstop){wait1Msec(1);}
			//startTask(Gunner);
			}
	}
}
